# Generated by Django 2.0.6 on 2018-11-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoEndPoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailies',
            old_name='username',
            new_name='title',
        ),
    ]
