# Generated by Django 2.0.6 on 2018-11-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoEndPoints', '0002_auto_20181129_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailies',
            name='reset',
            field=models.DateField(default=None),
        ),
    ]
