# Generated by Django 2.0.6 on 2018-11-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoEndPoints', '0003_dailies_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailies',
            name='resetTime',
            field=models.TimeField(default=None),
        ),
    ]
