# Generated by Django 2.0.6 on 2018-11-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoEndPoints', '0005_auto_20181129_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailies',
            name='reset',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
